# Dapr PostgreSQL State Store Component
# This component enables services to store and retrieve state from PostgreSQL

apiVersion: dapr.io/v1
kind: Component
metadata:
  name: learnflow-state
spec:
  type: state.postgresql
  version: v1
  metadata:
    # PostgreSQL connection string
    - name: connectionString
      value: "host=localhost port=5432 user=postgres password=postgres dbname=learnflow"

    # Table name for state storage
    - name: table
      value: "state"

    # Cleanup interval for expired state (seconds)
    - name: cleanupInterval
      value: "3600"

    # Maximum number of connections to the database
    - name: maxConns
      value: "10"

    # Query timeout in seconds
    - name: queryTimeout
      value: "30"

    # Maximum item count when using state queries
    - name: limit
      value: "100"
